# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\supportedATMs.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(378, 330)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QFrame {\n"
"background-color: black;\n"
"color: white;\n"
"    font: 8pt \"Roboto\";\n"
"}\n"
"\n"
"/* Scan Button Styling */\n"
"QPushButton {\n"
"  background-color: #FF9500; /* A bright orange for high visibility and action-inducement */\n"
"  color: red; /* Black text for high contrast on the orange button */\n"
"  font-size: 15px;\n"
"  font-weight: bold; /* Bold text to signify importance */\n"
"  padding: 10px; /* Generous padding to make the button touch-friendly */\n"
"  border: none; /* No border for a modern, flat design */\n"
"  border-radius: 5px; /* Slightly rounded corners for a modern look */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #E87C00; /* A slightly darker shade of orange for the hover state */\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setStyleSheet("font: 87 16pt \"Montserrat Black\";\n"
"color: #E8E8E8; /* A light grey color for subtlety against the black background */\n"
"font-family: \'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif; /* A more modern font choice */\n"
"font-weight: bold; /* Make the title bold */\n"
"text-align: center; /* Center-align the title */\n"
"\n"
"\n"
"")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(".\\images/atms-supported.png"))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Supported ATMS"))
