# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(871, 637)
        MainWindow.setStyleSheet("QMainWindow {\n"
"background-color: black;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QFrame {\n"
"background-color: black;\n"
"}\n"
"\n"
"/* Scan Button Styling */\n"
"#scanBtn {\n"
"  background-color: #FF9500; /* A bright orange for high visibility and action-inducement */\n"
"  color: red; /* Black text for high contrast on the orange button */\n"
"  font-family: \'Roboto\', sans-serif; /* A modern, friendly sans-serif font */\n"
"  font-size: 15px;\n"
"  font-weight: bold; /* Bold text to signify importance */\n"
"  padding: 10px; /* Generous padding to make the button touch-friendly */\n"
"  border: none; /* No border for a modern, flat design */\n"
"  border-radius: 5px; /* Slightly rounded corners for a modern look */\n"
"}\n"
"\n"
"#scanBtn:hover {\n"
"  background-color: #E87C00; /* A slightly darker shade of orange for the hover state */\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QPushButton {\n"
"background: tranpsarent;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.invisibleBtn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.invisibleBtn.sizePolicy().hasHeightForWidth())
        self.invisibleBtn.setSizePolicy(sizePolicy)
        self.invisibleBtn.setMinimumSize(QtCore.QSize(0, 65))
        self.invisibleBtn.setObjectName("invisibleBtn")
        self.horizontalLayout_2.addWidget(self.invisibleBtn)
        self.label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("font: 87 16pt \"Montserrat Black\";\n"
"color: #E8E8E8; /* A light grey color for subtlety against the black background */\n"
"font-family: \'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif; /* A more modern font choice */\n"
"font-weight: bold; /* Make the title bold */\n"
"text-align: center; /* Center-align the title */\n"
" border-bottom: 2px solid #4CAF50; /* A green border for emphasis and to tie in with button color */\n"
"  \n"
"\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.pushButton_12 = QtWidgets.QPushButton(self.frame)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_2.addWidget(self.pushButton_12)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setStyleSheet("QPushButton {\n"
"background: rgb(85, 85, 255);\n"
"font: 8pt \"Open Sans\";\n"
"font-size: 15px;\n"
"padding: 5px 3px;\n"
"border: 1px solid lightgrey;\n"
"color: lightgrey\n"
"}\n"
"\n"
"\n"
"\n"
"/* Style the buttons with a pop of color */\n"
"QPushButton {\n"
"  background-color: #4CAF50; /* A shade of green for visibility and contrast */\n"
"  color: white;\n"
"  font-family: \'Arial\', sans-serif;\n"
"  border: none;\n"
"  border-radius: 4px;\n"
"  padding: 10px 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #45a049; /* A slightly darker green for hover effect */\n"
"}\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.portBtn = QtWidgets.QPushButton(self.frame_3)
        self.portBtn.setObjectName("portBtn")
        self.verticalLayout_5.addWidget(self.portBtn)
        self.settingsBtn = QtWidgets.QPushButton(self.frame_3)
        self.settingsBtn.setObjectName("settingsBtn")
        self.verticalLayout_5.addWidget(self.settingsBtn)
        self.supportedBtn = QtWidgets.QPushButton(self.frame_3)
        self.supportedBtn.setObjectName("supportedBtn")
        self.verticalLayout_5.addWidget(self.supportedBtn)
        self.downloadPacketsBtn = QtWidgets.QPushButton(self.frame_3)
        self.downloadPacketsBtn.setObjectName("downloadPacketsBtn")
        self.verticalLayout_5.addWidget(self.downloadPacketsBtn)
        self.fileLocationBtn = QtWidgets.QPushButton(self.frame_3)
        self.fileLocationBtn.setObjectName("fileLocationBtn")
        self.verticalLayout_5.addWidget(self.fileLocationBtn)
        self.exitBtn = QtWidgets.QPushButton(self.frame_3)
        self.exitBtn.setObjectName("exitBtn")
        self.verticalLayout_5.addWidget(self.exitBtn)
        self.disconnectAllBtn = QtWidgets.QPushButton(self.frame_3)
        self.disconnectAllBtn.setStyleSheet("background-color: rgb(0, 170, 127)")
        self.disconnectAllBtn.setObjectName("disconnectAllBtn")
        self.verticalLayout_5.addWidget(self.disconnectAllBtn)
        self.horizontalLayout.addWidget(self.frame_3)
        self.mainContent = QtWidgets.QFrame(self.frame_2)
        self.mainContent.setStyleSheet("/* Main Content Area Styling */\n"
"#mainContent {\n"
"  background-color: #1C1C1C; /* Dark grey which is softer than pure black */\n"
"  color: #E8E8E8; /* Light grey text for readability */\n"
"  padding: 20px; /* Spacing inside the content area */\n"
"  border-radius: 8px; /* Softly rounded corners */\n"
"  margin: 20px; /* Space around the content area */\n"
"  }\n"
"\n"
"")
        self.mainContent.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainContent.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainContent.setObjectName("mainContent")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainContent)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.borderFrame = QtWidgets.QFrame(self.mainContent)
        self.borderFrame.setStyleSheet("#borderFrame {\n"
"border-radius: 15px;\n"
"}")
        self.borderFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.borderFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.borderFrame.setObjectName("borderFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.borderFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.blackFrame = QtWidgets.QFrame(self.borderFrame)
        self.blackFrame.setStyleSheet("")
        self.blackFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.blackFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.blackFrame.setObjectName("blackFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.blackFrame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_8 = QtWidgets.QFrame(self.blackFrame)
        self.frame_8.setStyleSheet("")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_8)
        self.label_2.setStyleSheet("color: lightgrey;\n"
"font: 87 10pt \"Montserrat Black\";\n"
"")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.scanBtn = QtWidgets.QPushButton(self.frame_8)
        self.scanBtn.setMaximumSize(QtCore.QSize(90, 100))
        self.scanBtn.setStyleSheet("\n"
"/* Scan Button Styling */\n"
"#scanBtn {\n"
"  background-color: #FF9500; /* A bright orange for high visibility and action-inducement */\n"
"  color: red; /* Black text for high contrast on the orange button */\n"
"  font-family: \'Roboto\', sans-serif; /* A modern, friendly sans-serif font */\n"
"  font-size: 15px;\n"
"  font-weight: bold; /* Bold text to signify importance */\n"
"  padding: 10px; /* Generous padding to make the button touch-friendly */\n"
"  border: none; /* No border for a modern, flat design */\n"
"  border-radius: 5px; /* Slightly rounded corners for a modern look */\n"
"}\n"
"\n"
"#scanBtn:hover {\n"
"  background-color: #E87C00; /* A slightly darker shade of orange for the hover state */\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\images/atm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.scanBtn.setIcon(icon)
        self.scanBtn.setIconSize(QtCore.QSize(25, 25))
        self.scanBtn.setObjectName("scanBtn")
        self.horizontalLayout_3.addWidget(self.scanBtn)
        self.verticalLayout_4.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.blackFrame)
        self.frame_9.setStyleSheet("")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_4 = QtWidgets.QFrame(self.frame_9)
        self.frame_4.setStyleSheet("QLabel {\n"
"color: lightgrey;\n"
"font-family: \'Roboto\', sans-serif; /* A modern, friendly sans-serif font */\n"
"font-size: 15px;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.statusLabel = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusLabel.sizePolicy().hasHeightForWidth())
        self.statusLabel.setSizePolicy(sizePolicy)
        self.statusLabel.setStyleSheet("color: red;")
        self.statusLabel.setObjectName("statusLabel")
        self.horizontalLayout_6.addWidget(self.statusLabel)
        self.verticalLayout_7.addWidget(self.frame_4)
        self.frame_6 = QtWidgets.QFrame(self.frame_9)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.signalTowerLabel = QtWidgets.QLabel(self.frame_6)
        self.signalTowerLabel.setStyleSheet("QLabel{\n"
"color: lightgrey;\n"
"font-family: \'Roboto\', sans-serif; /* A modern, friendly sans-serif font */\n"
"font-size: 15px;\n"
"}")
        self.signalTowerLabel.setObjectName("signalTowerLabel")
        self.horizontalLayout_7.addWidget(self.signalTowerLabel)
        self.verticalLayout_7.addWidget(self.frame_6)
        self.line = QtWidgets.QFrame(self.frame_9)
        self.line.setStyleSheet("background-color: green;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_7.addWidget(self.line)
        self.label_4 = QtWidgets.QLabel(self.frame_9)
        self.label_4.setStyleSheet("color: lightgrey;\n"
"font: 75 10pt \"Roboto Black\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.frame_9)
        self.label_3.setStyleSheet("color: lightgrey;\n"
"font: 10pt \"MS Sans Serif\";")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.frame_7 = QtWidgets.QFrame(self.frame_9)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_7.addWidget(self.frame_7)
        self.verticalLayout_4.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.blackFrame)
        self.frame_10.setStyleSheet("QProgressBar {\n"
"    border: 2px solid grey;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #4CAF50;\n"
"    width: 20px; /* size of the chunks */\n"
"    margin: 0.5px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #4CAF50;\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    border: none;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.startBtn = QtWidgets.QPushButton(self.frame_10)
        self.startBtn.setStyleSheet("\n"
"/* Scan Button Styling */\n"
"#startBtn {\n"
"  background-color: #FF9500; /* A bright orange for high visibility and action-inducement */\n"
"  font-family: \'Roboto\', sans-serif; /* A modern, friendly sans-serif font */\n"
"  font-size: 15px;\n"
"  font-weight: bold; /* Bold text to signify importance */\n"
"  padding: 10px 20px; /* Generous padding to make the button touch-friendly */\n"
"  border: none; /* No border for a modern, flat design */\n"
"  border-radius: 5px; /* Slightly rounded corners for a modern look */\n"
"}\n"
"\n"
"#startBtn:hover {\n"
"  background-color: #E87C00; /* A slightly darker shade of orange for the hover state */\n"
"}\n"
"")
        self.startBtn.setObjectName("startBtn")
        self.horizontalLayout_4.addWidget(self.startBtn)
        self.progressBar = QtWidgets.QProgressBar(self.frame_10)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_4.addWidget(self.progressBar)
        self.verticalLayout_4.addWidget(self.frame_10)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 5)
        self.verticalLayout_4.setStretch(2, 1)
        self.verticalLayout_3.addWidget(self.blackFrame)
        self.verticalLayout_2.addWidget(self.borderFrame)
        self.horizontalLayout.addWidget(self.mainContent)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setStyleSheet("QPushButton {\n"
"background: rgb(85, 85, 205);\n"
"font: 8pt \"Open Sans\";\n"
"font-size: 15px;\n"
"padding: 5px 3px;\n"
"border: 1px solid lightgrey;\n"
"color: white;\n"
"}\n"
"\n"
"\n"
"/* Style the buttons with a pop of color */\n"
"QPushButton {\n"
"  background-color: #4CAF50; /* A shade of green for visibility and contrast */\n"
"  color: white;\n"
"  font-family: \'Arial\', sans-serif;\n"
"  border: none;\n"
"  border-radius: 4px;\n"
"  padding: 10px 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #45a049; /* A slightly darker green for hover effect */\n"
"}\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.connectPCToGSMBtn = QtWidgets.QPushButton(self.frame_5)
        self.connectPCToGSMBtn.setObjectName("connectPCToGSMBtn")
        self.verticalLayout_6.addWidget(self.connectPCToGSMBtn)
        self.connectGSMToATMBtn = QtWidgets.QPushButton(self.frame_5)
        self.connectGSMToATMBtn.setObjectName("connectGSMToATMBtn")
        self.verticalLayout_6.addWidget(self.connectGSMToATMBtn)
        self.connectToTowerBtn = QtWidgets.QPushButton(self.frame_5)
        self.connectToTowerBtn.setObjectName("connectToTowerBtn")
        self.verticalLayout_6.addWidget(self.connectToTowerBtn)
        self.horizontalLayout.addWidget(self.frame_5)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 5)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 5)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GSM Bank Software"))
        self.invisibleBtn.setText(_translate("MainWindow", "CLICK ME"))
        self.label.setText(_translate("MainWindow", "GSM RS232 BANK SOFTWARE V1.2"))
        self.pushButton_12.setText(_translate("MainWindow", "PushButton"))
        self.portBtn.setText(_translate("MainWindow", "PORT"))
        self.settingsBtn.setText(_translate("MainWindow", "Settings"))
        self.supportedBtn.setText(_translate("MainWindow", "Supported \n"
"ATMS"))
        self.downloadPacketsBtn.setText(_translate("MainWindow", "Download \n"
"Packets"))
        self.fileLocationBtn.setText(_translate("MainWindow", "File Location"))
        self.exitBtn.setText(_translate("MainWindow", "Exit"))
        self.disconnectAllBtn.setText(_translate("MainWindow", "Disconnect \n"
"All"))
        self.label_2.setText(_translate("MainWindow", "SCAN GSM PACKETS IN RADIUS"))
        self.scanBtn.setText(_translate("MainWindow", "SCAN"))
        self.label_5.setText(_translate("MainWindow", "Network Connection"))
        self.label_7.setText(_translate("MainWindow", "Status:"))
        self.statusLabel.setText(_translate("MainWindow", "Not Connected"))
        self.signalTowerLabel.setText(_translate("MainWindow", "Signal Strength to Tower"))
        self.label_4.setText(_translate("MainWindow", "CONNECTED ATMS"))
        self.label_3.setText(_translate("MainWindow", "ATM(s) STATUS CONNECTIVITY"))
        self.startBtn.setText(_translate("MainWindow", "Start"))
        self.connectPCToGSMBtn.setText(_translate("MainWindow", "Connect \n"
"PC to GSM"))
        self.connectGSMToATMBtn.setText(_translate("MainWindow", "Connect \n"
"GSM to ATM"))
        self.connectToTowerBtn.setText(_translate("MainWindow", "Connect \n"
"Both to Tower"))
