# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 526)
        MainWindow.setStyleSheet("\n"
"QMainWindow {\n"
"    background-color:#1e1d23;\n"
"}\n"
"QDialog {\n"
"    background-color:#1e1d23;\n"
"}\n"
"QColorDialog {\n"
"    background-color:#1e1d23;\n"
"}\n"
"QTextEdit {\n"
"    background-color:#1e1d23;\n"
"    color: #a9b7c6;\n"
"}\n"
"QPlainTextEdit {\n"
"    selection-background-color:#007b50;\n"
"    background-color:#1e1d23;\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-width: 1px;\n"
"    color: #a9b7c6;\n"
"}\n"
"QPushButton{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    color: #a9b7c6;\n"
"    padding: 2px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QPushButton::default{\n"
"    border-style: inset;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #04b97f;\n"
"    border-width: 1px;\n"
"    color: #a9b7c6;\n"
"    padding: 2px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QToolButton {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #04b97f;\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: #a9b7c6;\n"
"    padding: 2px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QToolButton:hover{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #37efba;\n"
"    border-bottom-width: 2px;\n"
"    border-style: solid;\n"
"    color: #FFFFFF;\n"
"    padding-bottom: 1px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #37efba;\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: #FFFFFF;\n"
"    padding-bottom: 2px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #37efba;\n"
"    border-bottom-width: 2px;\n"
"    border-style: solid;\n"
"    color: #37efba;\n"
"    padding-bottom: 1px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QPushButton:disabled{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #808086;\n"
"    border-bottom-width: 2px;\n"
"    border-style: solid;\n"
"    color: #808086;\n"
"    padding-bottom: 1px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QLineEdit {\n"
"    border-width: 1px; border-radius: 4px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"    padding: 0 8px;\n"
"    color: #a9b7c6;\n"
"    background:#1e1d23;\n"
"    selection-background-color:#007b50;\n"
"    selection-color: #FFFFFF;\n"
"}\n"
"QLabel {\n"
"    color: #a9b7c6;\n"
"}\n"
"QLCDNumber {\n"
"    color: #37e6b4;\n"
"}\n"
"QProgressBar {\n"
"    text-align: center;\n"
"    color: rgb(240, 240, 240);\n"
"    border-width: 1px; \n"
"    border-radius: 10px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"    background-color:#1e1d23;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #04b97f;\n"
"    border-radius: 5px;\n"
"}\n"
"QMenuBar {\n"
"    background-color: #1e1d23;\n"
"}\n"
"QMenuBar::item {\n"
"    color: #a9b7c6;\n"
"      spacing: 3px;\n"
"      padding: 1px 4px;\n"
"      background: #1e1d23;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"      background:#1e1d23;\n"
"    color: #FFFFFF;\n"
"}\n"
"QMenu::item:selected {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: #04b97f;\n"
"    border-bottom-color: transparent;\n"
"    border-left-width: 2px;\n"
"    color: #FFFFFF;\n"
"    padding-left:15px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:7px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QMenu::item {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: #a9b7c6;\n"
"    padding-left:17px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:7px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QMenu{\n"
"    background-color:#1e1d23;\n"
"}\n"
"QTabWidget {\n"
"    color:rgb(0,0,0);\n"
"    background-color:#1e1d23;\n"
"}\n"
"QTabWidget::pane {\n"
"        border-color: rgb(77,77,77);\n"
"        background-color:#1e1d23;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-radius: 6px;\n"
"}\n"
"QTabBar::tab {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: #808086;\n"
"    padding: 3px;\n"
"    margin-left:3px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:last:selected, QTabBar::tab:hover {\n"
"      border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #04b97f;\n"
"    border-bottom-width: 2px;\n"
"    border-style: solid;\n"
"    color: #FFFFFF;\n"
"    padding-left: 3px;\n"
"    padding-bottom: 2px;\n"
"    margin-left:3px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    color: #a9b7c6;\n"
"    padding: 2px;\n"
"}\n"
"QCheckBox:disabled {\n"
"    color: #808086;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QCheckBox:hover {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    padding-left: 1px;\n"
"    padding-right: 1px;\n"
"    padding-bottom: 1px;\n"
"    padding-top: 1px;\n"
"    border-width:1px;\n"
"    border-color: rgb(87, 97, 106);\n"
"    background-color:#1e1d23;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: #04b97f;\n"
"    color: #a9b7c6;\n"
"    background-color: #04b97f;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: #04b97f;\n"
"    color: #a9b7c6;\n"
"    background-color: transparent;\n"
"}\n"
"QRadioButton {\n"
"    color: #a9b7c6;\n"
"    background-color: #1e1d23;\n"
"    padding: 1px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: #04b97f;\n"
"    color: #a9b7c6;\n"
"    background-color: #04b97f;\n"
"}\n"
"QRadioButton::indicator:!checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: #04b97f;\n"
"    color: #a9b7c6;\n"
"    background-color: transparent;\n"
"}\n"
"QStatusBar {\n"
"    color:#027f7f;\n"
"}\n"
"QSpinBox {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QDoubleSpinBox {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QTimeEdit {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QDateTimeEdit {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QDateEdit {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QComboBox {\n"
"    color: #a9b7c6;    \n"
"    background: #1e1d23;\n"
"}\n"
"QComboBox:editable {\n"
"    background: #1e1d23;\n"
"    color: #a9b7c6;\n"
"    selection-background-color: #1e1d23;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: #a9b7c6;    \n"
"    background: #1e1d23;\n"
"    selection-color: #FFFFFF;\n"
"    selection-background-color: #1e1d23;\n"
"}\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    color: #a9b7c6;    \n"
"    background: #1e1d23;\n"
"}\n"
"QFontComboBox {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QToolBox {\n"
"    color: #a9b7c6;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QToolBox::tab {\n"
"    color: #a9b7c6;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QToolBox::tab:selected {\n"
"    color: #FFFFFF;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QScrollArea {\n"
"    color: #FFFFFF;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    height: 5px;\n"
"    background: #04b97f;\n"
"}\n"
"QSlider::groove:vertical {\n"
"    width: 5px;\n"
"    background: #04b97f;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
"    border: 1px solid #5c5c5c;\n"
"    width: 14px;\n"
"    margin: -5px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background: qlineargradient(x1:1, y1:1, x2:0, y2:0, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
"    border: 1px solid #5c5c5c;\n"
"    height: 14px;\n"
"    margin: 0 -5px;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"    background: white;\n"
"}\n"
"QSlider::add-page:vertical {\n"
"    background: white;\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"    background: #04b97f;\n"
"}\n"
"QSlider::sub-page:vertical {\n"
"    background: #04b97f;\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"    border-style: solid;\n"
"    border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #d3dae3;\n"
"    padding: 2px;\n"
"    background-color: #100E19;\n"
"}\n"
"QPushButton::default{\n"
"    border-style: solid;\n"
"    border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #FFFFFF;\n"
"    padding: 2px;\n"
"    background-color: #151a1e;\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 #C0DB50, stop:0.4 #C0DB50, stop:0.5 #100E19, stop:1 #100E19);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 #100E19, stop:0.5 #100E19, stop:0.6 #C0DB50, stop:1 #C0DB50);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #C0DB50, stop:0.3 #C0DB50, stop:0.7 #100E19, stop:1 #100E19);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #C0DB50, stop:0.3 #C0DB50, stop:0.7 #100E19, stop:1 #100E19);\n"
"    border-width: 2px;\n"
"    border-radius: 1px;\n"
"    color: #d3dae3;\n"
"    padding: 2px;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 #d33af1, stop:0.4 #d33af1, stop:0.5 #100E19, stop:1 #100E19);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 #100E19, stop:0.5 #100E19, stop:0.6 #d33af1, stop:1 #d33af1);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #d33af1, stop:0.3 #d33af1, stop:0.7 #100E19, stop:1 #100E19);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #d33af1, stop:0.3 #d33af1, stop:0.7 #100E19, stop:1 #100E19);\n"
"    border-width: 2px;\n"
"    border-radius: 1px;\n"
"    color: #d3dae3;\n"
"    padding: 2px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_15 = QtWidgets.QFrame(self.frame_8)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_15)
        self.gridLayout.setObjectName("gridLayout")
        self.masterCardCheckBox = QtWidgets.QCheckBox(self.frame_15)
        self.masterCardCheckBox.setObjectName("masterCardCheckBox")
        self.gridLayout.addWidget(self.masterCardCheckBox, 2, 0, 1, 1)
        self.checkBox101 = QtWidgets.QCheckBox(self.frame_15)
        self.checkBox101.setObjectName("checkBox101")
        self.gridLayout.addWidget(self.checkBox101, 1, 2, 1, 1)
        self.visaCheckBox = QtWidgets.QCheckBox(self.frame_15)
        self.visaCheckBox.setObjectName("visaCheckBox")
        self.gridLayout.addWidget(self.visaCheckBox, 1, 0, 1, 1)
        self.debitCheckBox = QtWidgets.QCheckBox(self.frame_15)
        self.debitCheckBox.setObjectName("debitCheckBox")
        self.gridLayout.addWidget(self.debitCheckBox, 2, 1, 1, 1)
        self.creditCheckBox = QtWidgets.QCheckBox(self.frame_15)
        self.creditCheckBox.setObjectName("creditCheckBox")
        self.gridLayout.addWidget(self.creditCheckBox, 1, 1, 1, 1)
        self.discoverCheckBox = QtWidgets.QCheckBox(self.frame_15)
        self.discoverCheckBox.setObjectName("discoverCheckBox")
        self.gridLayout.addWidget(self.discoverCheckBox, 3, 0, 1, 1)
        self.emvChipCheckBox = QtWidgets.QCheckBox(self.frame_15)
        self.emvChipCheckBox.setObjectName("emvChipCheckBox")
        self.gridLayout.addWidget(self.emvChipCheckBox, 6, 2, 1, 1)
        self.amexCheckBox = QtWidgets.QCheckBox(self.frame_15)
        self.amexCheckBox.setObjectName("amexCheckBox")
        self.gridLayout.addWidget(self.amexCheckBox, 4, 0, 1, 1)
        self.allDebitCreditCheckBox = QtWidgets.QCheckBox(self.frame_15)
        self.allDebitCreditCheckBox.setObjectName("allDebitCreditCheckBox")
        self.gridLayout.addWidget(self.allDebitCreditCheckBox, 3, 1, 1, 1)
        self.checkBox201 = QtWidgets.QCheckBox(self.frame_15)
        self.checkBox201.setObjectName("checkBox201")
        self.gridLayout.addWidget(self.checkBox201, 2, 2, 1, 1)
        self.checkBox221 = QtWidgets.QCheckBox(self.frame_15)
        self.checkBox221.setObjectName("checkBox221")
        self.gridLayout.addWidget(self.checkBox221, 3, 2, 1, 1)
        self.checkBox121 = QtWidgets.QCheckBox(self.frame_15)
        self.checkBox121.setObjectName("checkBox121")
        self.gridLayout.addWidget(self.checkBox121, 4, 2, 1, 1)
        self.allemvChipCheckBox = QtWidgets.QCheckBox(self.frame_15)
        self.allemvChipCheckBox.setObjectName("allemvChipCheckBox")
        self.gridLayout.addWidget(self.allemvChipCheckBox, 7, 2, 1, 1)
        self.allVisaMasterCheckBox = QtWidgets.QCheckBox(self.frame_15)
        self.allVisaMasterCheckBox.setObjectName("allVisaMasterCheckBox")
        self.gridLayout.addWidget(self.allVisaMasterCheckBox, 6, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_15)
        self.label_7.setStyleSheet("\n"
"font: 10pt \"Montserrat ExtraBold\";")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(self.frame_8)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_17 = QtWidgets.QFrame(self.frame_16)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.frame_17)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.chooseTerminalComboBox = QtWidgets.QComboBox(self.frame_17)
        self.chooseTerminalComboBox.setObjectName("chooseTerminalComboBox")
        self.chooseTerminalComboBox.addItem("")
        self.chooseTerminalComboBox.addItem("")
        self.chooseTerminalComboBox.addItem("")
        self.horizontalLayout_6.addWidget(self.chooseTerminalComboBox)
        self.verticalLayout_9.addWidget(self.frame_17)
        self.frame_18 = QtWidgets.QFrame(self.frame_16)
        self.frame_18.setStyleSheet("QPushButton {\n"
"padding: 13px 5px;\n"
"}")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_10.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_10.setSpacing(4)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.resetNetworkBtn = QtWidgets.QPushButton(self.frame_18)
        self.resetNetworkBtn.setObjectName("resetNetworkBtn")
        self.verticalLayout_10.addWidget(self.resetNetworkBtn)
        self.refreshNetworkBtn = QtWidgets.QPushButton(self.frame_18)
        self.refreshNetworkBtn.setObjectName("refreshNetworkBtn")
        self.verticalLayout_10.addWidget(self.refreshNetworkBtn)
        self.showDataBtn = QtWidgets.QPushButton(self.frame_18)
        self.showDataBtn.setObjectName("showDataBtn")
        self.verticalLayout_10.addWidget(self.showDataBtn)
        self.verticalLayout_9.addWidget(self.frame_18)
        self.verticalLayout_9.setStretch(0, 1)
        self.verticalLayout_9.setStretch(1, 3)
        self.verticalLayout_8.addWidget(self.frame_16)
        self.horizontalLayout_3.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame_6)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setStyleSheet("")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("\n"
"font: 10pt \"Montserrat ExtraBold\";")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.resultsPlainText = QtWidgets.QPlainTextEdit(self.frame_10)
        self.resultsPlainText.setStyleSheet("border: 1px solid rgb(218, 218, 218);\n"
"border-radius: 10px;")
        self.resultsPlainText.setPlainText("")
        self.resultsPlainText.setObjectName("resultsPlainText")
        self.verticalLayout_7.addWidget(self.resultsPlainText)
        self.verticalLayout_5.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.frame_9)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_12 = QtWidgets.QFrame(self.frame_11)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_4 = QtWidgets.QLabel(self.frame_12)
        self.label_4.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 10pt \"Montserrat ExtraBold\";")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_11.addWidget(self.label_4)
        self.mainIconBtn = QtWidgets.QPushButton(self.frame_12)
        self.mainIconBtn.setStyleSheet("\n"
"background-color: white;\n"
"")
        self.mainIconBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/MAIN MIDDLE LOGO.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mainIconBtn.setIcon(icon)
        self.mainIconBtn.setIconSize(QtCore.QSize(50, 50))
        self.mainIconBtn.setObjectName("mainIconBtn")
        self.verticalLayout_11.addWidget(self.mainIconBtn)
        self.horizontalLayout_4.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.frame_11)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.helpBtn = QtWidgets.QPushButton(self.frame_13)
        self.helpBtn.setObjectName("helpBtn")
        self.verticalLayout_6.addWidget(self.helpBtn, 0, QtCore.Qt.AlignRight)
        self.closeBtn = QtWidgets.QPushButton(self.frame_13)
        self.closeBtn.setObjectName("closeBtn")
        self.verticalLayout_6.addWidget(self.closeBtn, 0, QtCore.Qt.AlignRight)
        self.connectToATMBtn = QtWidgets.QPushButton(self.frame_13)
        self.connectToATMBtn.setObjectName("connectToATMBtn")
        self.verticalLayout_6.addWidget(self.connectToATMBtn)
        self.connectToPOSBtn = QtWidgets.QPushButton(self.frame_13)
        self.connectToPOSBtn.setObjectName("connectToPOSBtn")
        self.verticalLayout_6.addWidget(self.connectToPOSBtn)
        self.frame_14 = QtWidgets.QFrame(self.frame_13)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.bluetoothCheckBox = QtWidgets.QCheckBox(self.frame_14)
        self.bluetoothCheckBox.setObjectName("bluetoothCheckBox")
        self.horizontalLayout_5.addWidget(self.bluetoothCheckBox)
        self.usbCheckBox = QtWidgets.QCheckBox(self.frame_14)
        self.usbCheckBox.setObjectName("usbCheckBox")
        self.horizontalLayout_5.addWidget(self.usbCheckBox)
        self.verticalLayout_6.addWidget(self.frame_14)
        self.horizontalLayout_4.addWidget(self.frame_13)
        self.verticalLayout_5.addWidget(self.frame_11)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 1)
        self.horizontalLayout_3.addWidget(self.frame_9)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_2)
        self.frame_7.setStyleSheet("")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, 50)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.exitBtn = QtWidgets.QPushButton(self.frame_7)
        self.exitBtn.setAcceptDrops(True)
        self.exitBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/EXIT LOGO.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitBtn.setIcon(icon1)
        self.exitBtn.setIconSize(QtCore.QSize(40, 30))
        self.exitBtn.setObjectName("exitBtn")
        self.verticalLayout_4.addWidget(self.exitBtn)
        self.readBtn = QtWidgets.QPushButton(self.frame_7)
        self.readBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/READ ICON.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.readBtn.setIcon(icon2)
        self.readBtn.setIconSize(QtCore.QSize(30, 30))
        self.readBtn.setObjectName("readBtn")
        self.verticalLayout_4.addWidget(self.readBtn)
        self.connectBtn = QtWidgets.QPushButton(self.frame_7)
        self.connectBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/CONNECT LOGO.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.connectBtn.setIcon(icon3)
        self.connectBtn.setIconSize(QtCore.QSize(30, 30))
        self.connectBtn.setObjectName("connectBtn")
        self.verticalLayout_4.addWidget(self.connectBtn)
        self.errorCheckBtn = QtWidgets.QPushButton(self.frame_7)
        self.errorCheckBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/ERROR CHECK ICON.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.errorCheckBtn.setIcon(icon4)
        self.errorCheckBtn.setIconSize(QtCore.QSize(30, 30))
        self.errorCheckBtn.setObjectName("errorCheckBtn")
        self.verticalLayout_4.addWidget(self.errorCheckBtn)
        self.saveDBBtn = QtWidgets.QPushButton(self.frame_7)
        self.saveDBBtn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/SAVE DB ICON.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveDBBtn.setIcon(icon5)
        self.saveDBBtn.setIconSize(QtCore.QSize(30, 30))
        self.saveDBBtn.setObjectName("saveDBBtn")
        self.verticalLayout_4.addWidget(self.saveDBBtn)
        self.importDBBtn = QtWidgets.QPushButton(self.frame_7)
        self.importDBBtn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/IMPORT DB ICON.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.importDBBtn.setIcon(icon6)
        self.importDBBtn.setIconSize(QtCore.QSize(30, 30))
        self.importDBBtn.setObjectName("importDBBtn")
        self.verticalLayout_4.addWidget(self.importDBBtn)
        self.horizontalLayout_2.addWidget(self.frame_7)
        self.horizontalLayout_2.setStretch(0, 4)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(60, 0))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.statusLabel = QtWidgets.QLabel(self.frame_4)
        self.statusLabel.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 10pt \"Montserrat ExtraBold\";")
        self.statusLabel.setObjectName("statusLabel")
        self.horizontalLayout.addWidget(self.statusLabel)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.progressBar = QtWidgets.QProgressBar(self.frame_5)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.frame_3)
        self.verticalLayout.setStretch(1, 5)
        self.verticalLayout.setStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BETA GSM RECIEVER ATM NETWORK 1.1"))
        self.masterCardCheckBox.setText(_translate("MainWindow", "MASTERCARD"))
        self.checkBox101.setText(_translate("MainWindow", "101"))
        self.visaCheckBox.setText(_translate("MainWindow", "VISA"))
        self.debitCheckBox.setText(_translate("MainWindow", "DEBIT"))
        self.creditCheckBox.setText(_translate("MainWindow", "CREDIT"))
        self.discoverCheckBox.setText(_translate("MainWindow", "DISCOVER"))
        self.emvChipCheckBox.setText(_translate("MainWindow", "EMV CHIP"))
        self.amexCheckBox.setText(_translate("MainWindow", "AMEX"))
        self.allDebitCreditCheckBox.setText(_translate("MainWindow", "ALL"))
        self.checkBox201.setText(_translate("MainWindow", "201"))
        self.checkBox221.setText(_translate("MainWindow", "221"))
        self.checkBox121.setText(_translate("MainWindow", "121"))
        self.allemvChipCheckBox.setText(_translate("MainWindow", "ALL"))
        self.allVisaMasterCheckBox.setText(_translate("MainWindow", "ALL"))
        self.label_7.setText(_translate("MainWindow", "Select Options"))
        self.label_6.setText(_translate("MainWindow", "Choose Terminal:"))
        self.chooseTerminalComboBox.setItemText(0, _translate("MainWindow", "Auto"))
        self.chooseTerminalComboBox.setItemText(1, _translate("MainWindow", "Manual"))
        self.chooseTerminalComboBox.setItemText(2, _translate("MainWindow", "Proxy"))
        self.resetNetworkBtn.setText(_translate("MainWindow", "Reset Network"))
        self.refreshNetworkBtn.setText(_translate("MainWindow", "Refresh Network"))
        self.showDataBtn.setText(_translate("MainWindow", "Show Data"))
        self.label_3.setText(_translate("MainWindow", "RESULTS"))
        self.label_4.setText(_translate("MainWindow", "NOT CONNECTED"))
        self.helpBtn.setText(_translate("MainWindow", "HELP"))
        self.closeBtn.setText(_translate("MainWindow", "CLOSE"))
        self.connectToATMBtn.setText(_translate("MainWindow", "CONNECT TO ATM"))
        self.connectToPOSBtn.setText(_translate("MainWindow", "CONNECT TO POS"))
        self.bluetoothCheckBox.setText(_translate("MainWindow", "BLUETOOTH"))
        self.usbCheckBox.setText(_translate("MainWindow", "USB"))
        self.exitBtn.setToolTip(_translate("MainWindow", "Exit the Application"))
        self.readBtn.setToolTip(_translate("MainWindow", "Read"))
        self.connectBtn.setToolTip(_translate("MainWindow", "Connect"))
        self.errorCheckBtn.setToolTip(_translate("MainWindow", "Check Errors"))
        self.saveDBBtn.setToolTip(_translate("MainWindow", "Download DB"))
        self.importDBBtn.setToolTip(_translate("MainWindow", "Import DB"))
        self.label.setText(_translate("MainWindow", "STATUS:"))
        self.statusLabel.setText(_translate("MainWindow", "NOT CONNECTED"))
import resources_rc
